sudo: false

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libasound2-dev

language: node_js

node_js:
  - '12'
  - '10'
  - '8'
  - '8.6.0'
